spring.application.name=vodici-service
spring.config.import=optional:configserver:http://localhost:8888
avanture.service.url=${AVANTURE_SERVICE_URL:http://localhost:8086}
management.tracing.sampling.probability=1.0
management.tracing.propagation.type=w3c
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
loki.url=${LOKI_URL:http://localhost:3100/loki/api/v1/push}
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
logging.pattern.level=%5p [traceId:%X{traceId:-}] [spanId:%X{spanId:-}] [user:%X{authenticatedUser:-anonymous}] [role:%X{userRole:-unknown}]
