create table if not exists guests (
    id bigint generated by default as identity primary key,
    first_name varchar(80) not null,
    last_name varchar(80) not null,
    email varchar(120) not null unique
);

create table if not exists cancellation_policies (
    id bigint generated by default as identity primary key,
    policy_name varchar(100) not null unique,
    refund_percentage decimal(5, 2) not null
);

create table if not exists bookings (
    id bigint generated by default as identity primary key,
    unit_id bigint not null,
    guest_id bigint not null,
    policy_id bigint,
    start_date date not null,
    end_date date not null,
    total_price decimal(10, 2) not null,
    status varchar(32) not null,
    constraint fk_bookings_guest foreign key (guest_id) references guests(id),
    constraint fk_bookings_policy foreign key (policy_id) references cancellation_policies(id)
);

create table if not exists add_on_items (
    id bigint generated by default as identity primary key,
    booking_id bigint not null,
    service_name varchar(100) not null,
    price decimal(10, 2) not null,
    constraint fk_add_on_items_booking foreign key (booking_id) references bookings(id)
);

create table if not exists booking_status_logs (
    id bigint generated by default as identity primary key,
    booking_id bigint not null,
    old_status varchar(32),
    new_status varchar(32) not null,
    changed_at timestamp not null,
    note varchar(255),
    constraint fk_booking_status_logs_booking foreign key (booking_id) references bookings(id)
);
