spring.application.name=finance-service
server.port=8080
server.error.include-message=always
booking-service.base-url=http://localhost:8084
logging.level.org.example.financeservice.integration=INFO
logging.level.io.github.resilience4j=INFO

spring.datasource.url=jdbc:mysql://localhost:3307/financedb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=optional:classpath:/disabled-schema.sql
spring.sql.init.data-locations=classpath:data.sql

management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreakerevents,retries,retryevents
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.propagation.type=w3c
management.tracing.sampling.probability=1.0

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

resilience4j.circuitbreaker.instances.bookingServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.bookingServiceCircuitBreaker.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.bookingServiceCircuitBreaker.slidingWindowSize=5
resilience4j.circuitbreaker.instances.bookingServiceCircuitBreaker.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.bookingServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.bookingServiceCircuitBreaker.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.bookingServiceCircuitBreaker.waitDurationInOpenState=20s
resilience4j.circuitbreaker.instances.bookingServiceCircuitBreaker.eventConsumerBufferSize=20

resilience4j.retry.instances.bookingServiceRetry.maxAttempts=3
resilience4j.retry.instances.bookingServiceRetry.waitDuration=500ms
resilience4j.retry.instances.bookingServiceRetry.enableExponentialBackoff=true
resilience4j.retry.instances.bookingServiceRetry.exponentialBackoffMultiplier=2
