create table if not exists tax_rates (
    id bigint generated by default as identity primary key,
    tax_name varchar(100) not null unique,
    percentage decimal(5, 2) not null
);

create table if not exists payment_methods (
    id bigint generated by default as identity primary key,
    method_name varchar(80) not null,
    is_active boolean not null
);

create table if not exists invoices (
    id bigint generated by default as identity primary key,
    booking_id bigint not null,
    tax_rate_id bigint not null,
    subtotal decimal(10, 2) not null,
    total_amount decimal(10, 2) not null,
    status varchar(32) not null,
    constraint fk_invoices_tax_rate foreign key (tax_rate_id) references tax_rates(id)
);

create table if not exists transactions (
    id bigint generated by default as identity primary key,
    invoice_id bigint not null,
    payment_method_id bigint not null,
    amount decimal(10, 2) not null,
    transaction_date timestamp not null,
    constraint fk_transactions_invoice foreign key (invoice_id) references invoices(id),
    constraint fk_transactions_payment_method foreign key (payment_method_id) references payment_methods(id)
);
