# Naziv aplikacije i port na kome radi
spring.application.name=avanture-service
server.port=8086

# Datasource (moved to docker-compose)
#spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/avantureservis?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.username=${DB_USERNAME:root}
#spring.datasource.password=${DB_PASSWORD:root}
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

# Swagger dokumentacija (interfejs za testiranje endpointa)
# Putanja: http://localhost:8086/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html

# Konfiguracija instance osiguraca
resilience4j.circuitbreaker.instances.vodiciServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.vodiciServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.vodiciServiceCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.vodiciServiceCB.permittedNumberOfCallsInHalfOpenState=3

# Rate Limit
resilience4j.ratelimiter.instances.vodiciServiceRateLimit.limit-for-period=10
resilience4j.ratelimiter.instances.vodiciServiceRateLimit.limit-refresh-period=1s
resilience4j.ratelimiter.instances.vodiciServiceRateLimit.timeout-duration=100ms


# Eksponiranje Actuator endpoint-a
#management.endpoints.web.exposure.include=health,circuitbreakers
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# Povezivanje Resilience4j sa Health sistemom
resilience4j.circuitbreaker.instances.vodiciServiceCB.registerHealthIndicator=true

# Opciono: Smanjenje prenatrpanosti logova za Feign i Resilience4j
logging.level.org.springframework.cloud.openfeign=WARN
logging.level.io.github.resilience4j.circuitbreaker=DEBUG
logging.file.name=logs/avanture-service.log
# Da se vidi tacno sta Resilience4j radi
logging.level.io.github.resilience4j=DEBUG

springdoc.api-docs.path=/api/avanture/v3/api-docs

# Vodici service URL
vodici.service.url=http://vodici-service:8087

# Feign
feign.client.config.default.connect-timeout=3000
feign.client.config.default.read-timeout=3000

# Dozvoljava Swagger-u sa porta 8083 da povuce dokumentaciju
springdoc.api-docs.enabled=true
springdoc.server.url=http://localhost:8083
management.endpoints.web.cors.allowed-origins=http://localhost:8083
management.endpoints.web.cors.allowed-methods=GET,POST,PUT,DELETE

# Objedinjeni Actuator endpointi (za zdravlje, CB i refresh configa)
management.endpoints.web.exposure.include=health,circuitbreakers,refresh
management.tracing.sampling.probability=1.0
management.tracing.propagation.type=w3c
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
loki.url=http://loki:3100/loki/api/v1/push
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=true
logging.pattern.level=%5p [traceId:%X{traceId:-}] [spanId:%X{spanId:-}] [user:%X{authenticatedUser:-anonymous}] [role:%X{userRole:-unknown}]





