# Server
server.port=8081

# Datasource (moved to docker-compose)
#spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/smestajservis?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.username=${DB_USERNAME:root}
#spring.datasource.password=${DB_PASSWORD:root}
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.defer-datasource-initialization=true
#spring.jpa.show-sql=true
#spring.sql.init.mode=always

# Remote service URL (used by OdrzavanjeClient)
smestaj.odrzavanje.url=http://odrzavanje:8082

# Eureka - service registry
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}

# Actuator — include 'refresh' for dynamic config reload
management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents,ratelimiters,refresh
management.endpoint.health.show-details=always
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.propagation.type=w3c

# Logging
logging.level.io.github.resilience4j.retry=DEBUG

# Circuit Breaker
resilience4j.circuitbreaker.instances.odrzavanjeService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.odrzavanjeService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.odrzavanjeService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.odrzavanjeService.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.odrzavanjeService.permittedNumberOfCallsInHalfOpenState=3

# Retry
resilience4j.retry.instances.odrzavanjeService.maxAttempts=3
resilience4j.retry.instances.odrzavanjeService.waitDuration=500ms
resilience4j.retry.instances.odrzavanjeService.retryExceptions=feign.RetryableException

# Timelimiter
resilience4j.timelimiter.instances.odrzavanjeService.timeoutDuration=5s

# Rate Limiters
resilience4j.ratelimiter.instances.createUnit.limit-for-period=3
resilience4j.ratelimiter.instances.createUnit.limit-refresh-period=60s
resilience4j.ratelimiter.instances.createUnit.timeout-duration=0s

resilience4j.ratelimiter.instances.createReservation.limit-for-period=10
resilience4j.ratelimiter.instances.createReservation.limit-refresh-period=60s
resilience4j.ratelimiter.instances.createReservation.timeout-duration=0s
#pozovi 8081/actuator/refresh kako bih refresovao na servisu 8081
